spring:
  application:
    name: cars
  datasource:
    url: jdbc:h2:mem:db
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  server:
    port: 8080
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
